title:My first Blog
author: xcs
email: 398229144@qq.com
description: > # this means to ignore newlines until "baseurl:"
  I'm a fresh-new starter in github-region, i will keep learning on it to improve myself.

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal
